# Generated by Django 5.1 on 2024-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('comuna', models.CharField(db_column='Comuna', primary_key=True, serialize=False)),
                ('region', models.CharField(db_column='Region')),
            ],
            options={
                'db_table': 'comunas',
                'managed': False,
            },
        ),
    ]
